version: "3"

services:
    local:
        image: local-tomcat-debug:SNAPSHOT
        hostname: tomcat8-sample-local
        container_name: sample-container
        ports:
            - "8080:8080"
            - "8009:8009"
            - "8000:8000"
        volumes:
            - "./image/resources/logs:/opt/tomcat/logs/"
            - "./image/resources/conf:/opt/tomcat/conf/"
            - "../../../target/empleo#sample.war:/opt/tomcat/webapps/empleo#sample.war"
#        environment:
#            - CATALINA_OPTS=-Dcom.sun.management.jmxremote
#            - Dcom.sun.management.jmxremote.port=9000
#            - Dcom.sun.management.jmxremote.rmi.port=9000
#            - Djava.rmi.server.hostname=127.0.0.1
#            - Dcom.sun.management.jmxremote.ssl=false
#            - Dcom.sun.management.jmxremote.authenticate=false
#            - Dcom.sun.management.jmxremote.local.only=false